package mycelium:session-bridge@0.1.0;

world session-bridge {
    export mycelium:pairing/pairing@0.1.0;
    export wasmcloud:messaging/handler@0.2.0;

    import wasmcloud:messaging/consumer@0.2.0;
    import wasi:keyvalue/store@0.2.0-draft;
    import wasi:keyvalue/atomics@0.2.0-draft;
    import wasi:logging/logging@0.1.0-draft;
    import wasi:clocks/wall-clock@0.2.2;
    import wasi:random/random@0.2.2;

    import mycelium:types/types@0.1.0;
}
