package mycelium:tool-time@0.1.0;

world tool-time {
    export wasmcloud:messaging/handler@0.2.0;

    import wasmcloud:messaging/consumer@0.2.0;
    import wasi:logging/logging@0.1.0-draft;
    import wasi:clocks/wall-clock@0.2.2;
}
