[package]
name              = "agent-registry"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wit-bindgen = { workspace = true }
serde       = { workspace = true }
serde_json  = { workspace = true }

[package.metadata.component]
package = "mycelium:agent-registry"

[package.metadata.component.target]
path  = "wit"
world = "agent-registry"

[package.metadata.component.target.dependencies]
"wasi:keyvalue" = { path = "wit/deps/wasi-keyvalue-0.2.0-draft" }
"wasi:logging"  = { path = "wit/deps/wasi-logging-0.1.0-draft" }
"wasi:clocks"   = { path = "wit/deps/wasi-clocks-0.2.2" }
"wasi:io"       = { path = "wit/deps/wasi-io-0.2.2" }
"mycelium:types" = { path = "wit/deps/mycelium-types-0.1.0" }
"mycelium:agent" = { path = "wit/deps/mycelium-agent-0.1.0" }
