[package]
name              = "telegram-gateway"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wit-bindgen = { workspace = true }
serde       = { workspace = true }
serde_json  = { workspace = true }
anyhow      = { workspace = true }
mycelium-types    = { workspace = true }

[package.metadata.component]
package = "mycelium:telegram-gateway"

[package.metadata.component.target]
path  = "wit"
world = "telegram-gateway"
