[package]
name              = "mycelium-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "mycelium-core"
path = "src/main.rs"

[dependencies]
async-nats         = { workspace = true }
futures-util       = { workspace = true }
tokio              = { workspace = true }
serde              = { workspace = true }
serde_json         = { workspace = true }
anyhow             = { workspace = true }
uuid               = { workspace = true }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
reqwest            = { workspace = true }
chrono             = { workspace = true }
thiserror          = { workspace = true }
bytes              = { workspace = true }
toml               = { workspace = true }
dotenvy            = { workspace = true }
mycelium-types        = { workspace = true }
mycelium-agent-core   = { workspace = true }
mycelium-tool-core    = { workspace = true }
