[package]
name              = "tool-runner"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wit-bindgen  = { workspace = true }
serde        = { workspace = true }
serde_json   = { workspace = true }
anyhow       = { workspace = true }
mycelium-types     = { workspace = true }
mycelium-tool-core = { workspace = true }

[package.metadata.component]
package = "mycelium:tool-runner"

[package.metadata.component.target]
path  = "wit"
world = "tool-runner"

[package.metadata.component.target.dependencies]
"wasi:http" = { path = "wit/deps/wasi-http-0.2.2" }
"wasi:io" = { path = "wit/deps/wasi-io-0.2.2" }
"wasi:keyvalue" = { path = "wit/deps/wasi-keyvalue-0.2.0-draft" }
"wasi:config" = { path = "wit/deps/wasi-config-0.2.0-rc.1" }
"wasi:logging" = { path = "wit/deps/wasi-logging-0.1.0-draft" }
"wasi:clocks" = { path = "wit/deps/wasi-clocks-0.2.2" }
"wasmcloud:messaging" = { path = "wit/deps/wasmcloud-messaging-0.2.0" }
"mycelium:types" = { path = "wit/deps/mycelium-types-0.1.0" }
"mycelium:tool" = { path = "wit/deps/mycelium-tool-0.1.0" }
"wasi:cli" = { path = "wit/deps/wasi-cli-0.2.2" }
"wasi:random" = { path = "wit/deps/wasi-random-0.2.2" }
