package mycelium:memory-store@0.1.0;

world memory-store {
    export wasmcloud:messaging/handler@0.2.0;
    export mycelium:memory/memory@0.1.0;

    import wasi:keyvalue/store@0.2.0-draft;
    import wasi:keyvalue/atomics@0.2.0-draft;
    import wasi:logging/logging@0.1.0-draft;
    import wasi:clocks/wall-clock@0.2.2;

    import mycelium:types/types@0.1.0;
}
